/**
 * STEAK
 * Kantinen-API
 *
 * OpenAPI spec version: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * A description for an offer, usually a dish, salad, etc.
 */
export interface Offer {
    /**
     * ...
     */
    description: string;

    /**
     * ...
     */
    _id?: string;

    /**
     * ...
     */
    price: number;

    /**
     * ...
     */
    date: Date | string;

    /**
     * Frühstück / Mittags
     */
    time: string;

    /**
     * Main meal or side dish. Side dishes would be a salad or a soup, eggs in the morning, ...
     */
    main_offer: boolean;

    /**
     * ...
     */
    vegetarian: boolean;

    /**
     * Describes the heat at which the offer was cooked. Needed for health governance
     */
    heat: number;

}
