/**
 * STEAK
 * Kantinen-API
 *
 * OpenAPI spec version: 0.0.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface User {
    /**
     * The three letter shortcut code for the employee
     */
    employeeId: string;

    openPaymentsSum: number;

    offersordersoverviewUrl?: string;

}
